# Dayfox tmux theme (colors pulled from EdenEast/nightfox.nvim's dayfox palette)

set -g status-style "bg=#e4dcd4,fg=#643f61"
set -g pane-border-style "fg=#d3c7bb"
set -g pane-active-border-style "fg=#2848a9"

set -g message-style "bg=#2848a9,fg=#f6f2ee"
set -g message-command-style "bg=#2848a9,fg=#f6f2ee"

set -g window-status-style "bg=#e4dcd4,fg=#824d5b"
set -g window-status-current-style "bg=#2848a9,fg=#f6f2ee,bold"
set -g window-status-activity-style "bg=#e4dcd4,fg=#AC5402"

set -g status-left-length 30
set -g status-left "#[bg=#2848a9,fg=#f6f2ee,bold] #S #[bg=#e4dcd4,fg=#2848a9]"
set -g status-right "#[fg=#824d5b]%Y-%m-%d %H:%M "
